
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arnaud
 */
public class TrafficLigtht extends javax.swing.JPanel {

    public void LightRed() {
        redLight.setOn(true);
        greenLight.setOn(false);
        orangeLight.setOn(false);
        repaint();
    }
    
    public void SwitchOffAll() {
        redLight.setOn(false);
        greenLight.setOn(false);
        orangeLight.setOn(false);repaint();
    }

    public void LightOrange() {
        redLight.setOn(false);
        greenLight.setOn(false);
        orangeLight.setOn(true);repaint();
    }

    public void LightGreen() {
        redLight.setOn(false);
        greenLight.setOn(true);
        orangeLight.setOn(false);repaint();
    }
    
    public void LightRedOrange() {
        redLight.setOn(true);
        greenLight.setOn(false);
        orangeLight.setOn(true);repaint();
    }
    
    /**
     * Creates new form TrafficLigtht
     */
    public TrafficLigtht() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redLight = new Light();
        orangeLight = new Light();
        greenLight = new Light();

        redLight.setBackground(new java.awt.Color(102, 102, 102));
        redLight.setColor(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout redLightLayout = new javax.swing.GroupLayout(redLight);
        redLight.setLayout(redLightLayout);
        redLightLayout.setHorizontalGroup(
            redLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        redLightLayout.setVerticalGroup(
            redLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        orangeLight.setBackground(new java.awt.Color(102, 102, 102));
        orangeLight.setColor(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout orangeLightLayout = new javax.swing.GroupLayout(orangeLight);
        orangeLight.setLayout(orangeLightLayout);
        orangeLightLayout.setHorizontalGroup(
            orangeLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        orangeLightLayout.setVerticalGroup(
            orangeLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        greenLight.setBackground(new java.awt.Color(102, 102, 102));
        greenLight.setColor(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout greenLightLayout = new javax.swing.GroupLayout(greenLight);
        greenLight.setLayout(greenLightLayout);
        greenLightLayout.setHorizontalGroup(
            greenLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        greenLightLayout.setVerticalGroup(
            greenLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greenLight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangeLight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redLight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(redLight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(orangeLight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(greenLight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Light greenLight;
    private Light orangeLight;
    private Light redLight;
    // End of variables declaration//GEN-END:variables
}
