/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meteoclic;

/**
 *
 * @author arnaud
 */
public class Fenetre extends javax.swing.JFrame {

    private void affichPluie() {
        meteo.setText("PLUIE");
    }

    private void affichSoleil() {
        meteo.setText("SOLEIL");
    }

    private void affichOrage() {
        meteo.setText("ORAGE");
    }

    private void affichPouf() {
        meteo.setText("POUF");
    }

    private void affichNuage() {
        meteo.setText("NUAGE");
    }

    private enum State {

        E1, E2
    };
    private State sf;
    private int cpt;

    private void activation() {
        switch (sf) {
            case E1:
                bStart.setEnabled(true);
                bStop.setEnabled(false);
                bPlus.setEnabled(false);
                break;
            case E2:
                bStart.setEnabled(false);
                bStop.setEnabled(true);
                bPlus.setEnabled(true);
                break;
        }
    }

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
        sf = State.E1;
        cpt = 0;
        affichSoleil();
        activation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bStart = new javax.swing.JButton();
        bStop = new javax.swing.JButton();
        bPlus = new javax.swing.JButton();
        meteo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bStart.setText("Start");
        bStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartActionPerformed(evt);
            }
        });

        bStop.setText("Stop");
        bStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStopActionPerformed(evt);
            }
        });

        bPlus.setText("+1");
        bPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlusActionPerformed(evt);
            }
        });

        meteo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bStart)
                .addGap(86, 86, 86)
                .addComponent(bStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(bPlus)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(meteo)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(meteo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bStart)
                    .addComponent(bStop)
                    .addComponent(bPlus))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlusActionPerformed
        switch (sf) {
            case E1:
                throw new RuntimeException("B1plus - E1");
            case E2:
                switch (cpt) {
                    case 0:
                        sf = State.E2;
                        cpt++;
                        affichNuage();
                        activation();
                        break;
                    case 1:
                        affichPluie();
                        cpt++;
                        sf = State.E2;
                        activation();
                        break;
                    case 2:
                        affichOrage();
                        cpt++;
                        sf = State.E2;
                        activation();
                        break;
                    case 3:
                        affichPouf();
                        cpt++;
                        sf = State.E1;
                        activation();
                        break;
                }
        }
    }//GEN-LAST:event_bPlusActionPerformed

    private void bStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStopActionPerformed
        switch (sf) {
            case E1:
                throw new RuntimeException("Bstop - E1");
            case E2:
                sf = State.E1;
                cpt = 0;
                affichPouf();
                activation();
        }
    }//GEN-LAST:event_bStopActionPerformed

    private void bStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartActionPerformed
        switch (sf) {
            case E1:
                sf = State.E2;
                cpt = 0;
                affichSoleil();
                activation();
                break;
            case E2:
                throw new RuntimeException("Bstart - E1");
                
        }
    }//GEN-LAST:event_bStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPlus;
    private javax.swing.JButton bStart;
    private javax.swing.JButton bStop;
    private javax.swing.JLabel meteo;
    // End of variables declaration//GEN-END:variables
}
